spring.application.name=stylemax-api

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

mercadopago.access-token=${MP_ACCESS_TOKEN:}

pedido.expiracion-minutos=${PEDIDO_EXPIRACION_MINUTOS:15}
pedido.expiracion-check-rate-ms=${PEDIDO_EXPIRACION_CHECK_MS:300000}

app.frontend-url=${APP_FRONTEND_URL:http://localhost:4200}
app.backend-url=${APP_BACKEND_URL:http://localhost:8081}

server.port=${DB_PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect